"use client";

import { useState, useEffect } from "react";
import { useWizardStore } from "../../store/wizardStore";
import { LoadingBlock } from "../ui/Spinner";
import { Button } from "../ui/Button";
import { RevisePanel } from "../ui/RevisePanel";
import { runParse, runChef, runEngineer, runSilhouettes } from "../../lib/api";
import { NutritionFactsTable } from "../chef/NutritionFactsTable";
import type { SyringeRecipe } from "../../lib/types";

// ─────────────────────────────────────────────────────────────────────────────
// Design tokens — matches homepage / profile page aesthetic
// ─────────────────────────────────────────────────────────────────────────────

const T = {
  ink:       "#1A1410",
  muted:     "#6B5D50",
  card:      "#FFFFFF",
  border:    "rgba(26, 20, 16, 0.12)",
  forest:    "rgb(21, 60, 54)",
  forestInk: "#FFF4E6",
  cream:     "rgb(244, 244, 232)",
  badge:     "#354f22",
  danger:    "#c0392b",
  dangerBg:  "#fff0f0",
};

// ─────────────────────────────────────────────────────────────────────────────
// Shared micro-components
// ─────────────────────────────────────────────────────────────────────────────

function BookmarkIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none"
      stroke={T.muted} strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">
      <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z" />
    </svg>
  );
}

function Spinner() {
  return (
    <svg width="16" height="16" viewBox="0 0 20 20"
      style={{ animation: "spin 0.8s linear infinite", flexShrink: 0 }}>
      <circle cx="10" cy="10" r="8" fill="none" stroke="currentColor" strokeWidth="2" strokeOpacity="0.25" />
      <path d="M10 2 A8 8 0 0 1 18 10" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
    </svg>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// SyringeRecipeCard
// ─────────────────────────────────────────────────────────────────────────────

function SyringeRecipeCardV2({ recipe }: { recipe: SyringeRecipe }) {
  return (
    <div style={{ background: T.card, border: `1.5px solid ${T.border}`, borderRadius: 16, overflow: "hidden" }}>
      <div style={{ padding: "18px 20px" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
          <span style={{
            width: 30, height: 30, borderRadius: "50%",
            background: T.badge, color: "#fff",
            display: "flex", alignItems: "center", justifyContent: "center",
            fontSize: 13, fontWeight: 700, flexShrink: 0,
            fontFamily: "'Geist Mono', monospace",
          }}>
            {recipe.syringe_id}
          </span>
          <div>
            <div style={{ fontSize: 14, fontWeight: 600, color: T.ink, fontFamily: "'Geist', sans-serif" }}>
              {recipe.title}
            </div>
            <div style={{ fontSize: 11, color: T.muted, fontFamily: "'Geist Mono', monospace",
              textTransform: "uppercase", letterSpacing: "0.06em", marginTop: 1 }}>
              {recipe.label}
            </div>
          </div>
        </div>

        <div style={{ height: "1px", background: T.border, margin: "0 0 14px" }} />

        <div style={{ marginBottom: 14 }}>
          <div style={{ fontSize: 10, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em",
            color: T.muted, marginBottom: 6, fontFamily: "'Geist Mono', monospace" }}>
            Ingredients
          </div>
          <ul style={{ margin: 0, padding: "0 0 0 16px" }}>
            {recipe.ingredients.map((ing, i) => (
              <li key={i} style={{ fontSize: 13, color: T.ink, lineHeight: 1.7, fontFamily: "'Geist', sans-serif" }}>
                {ing}
              </li>
            ))}
          </ul>
        </div>

        {recipe.instructions.length > 0 && (
          <div>
            <div style={{ fontSize: 10, fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.08em",
              color: T.muted, marginBottom: 6, fontFamily: "'Geist Mono', monospace" }}>
              Preparation
            </div>
            <ol style={{ margin: 0, padding: "0 0 0 16px" }}>
              {recipe.instructions.map((step, i) => (
                <li key={i} style={{ fontSize: 13, color: T.ink, lineHeight: 1.7, fontFamily: "'Geist', sans-serif" }}>
                  {step}
                </li>
              ))}
            </ol>
          </div>
        )}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Form Selection — 3 SVG silhouette variants generated by Claude
// ─────────────────────────────────────────────────────────────────────────────

type ShapeVariant = { label: string; description: string; svg: string | null };

const SKELETON_BG = `linear-gradient(90deg, #e8e3db 25%, #f0ece4 50%, #e8e3db 75%)`;

function ShimmerBlock({ width, height, radius = 8 }: { width: number | string; height: number | string; radius?: number }) {
  return (
    <div style={{
      width, height, borderRadius: radius,
      background: SKELETON_BG, backgroundSize: "300% 100%",
      animation: "shimmer 1.6s ease infinite",
    }} />
  );
}

/** Render SVG string safely — only called with Claude-generated content from our own backend */
function SvgPreview({ svg, size }: { svg: string; size: number }) {
  const patched = svg.replace("<svg", `<svg style="width:${size}px;height:${size}px"`);
  return <div dangerouslySetInnerHTML={{ __html: patched }} />;
}

function ContourPreviewV2({
  shapeName,
  onSelect,
  onSelectSvg,
}: {
  shapeName: string;
  onSelect?: () => void;
  onSelectSvg?: (svg: string) => void;
}) {
  const [selected, setSelected] = useState(0);
  const [variants, setVariants] = useState<ShapeVariant[]>([
    { label: "Upright",  description: "Standing pose", svg: null },
    { label: "Profile",  description: "Side view",     svg: null },
    { label: "Compact",  description: "Rounded form",  svg: null },
  ]);
  const [fetching, setFetching] = useState(!!shapeName);

  const displayName = shapeName
    ? shapeName.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
    : "Shape";

  useEffect(() => {
    if (!shapeName) { setFetching(false); return; }
    setFetching(true);
    setSelected(0);
    setVariants([
      { label: "Upright", description: "Standing pose", svg: null },
      { label: "Profile",  description: "Side view",    svg: null },
      { label: "Compact",  description: "Rounded form", svg: null },
    ]);
    runSilhouettes(shapeName)
      .then(({ variants: fetched }) => {
        const updated = fetched.map((v) => ({ label: v.label, description: v.description, svg: v.svg }));
        setVariants(updated);
        if (updated[0]?.svg) onSelectSvg?.(updated[0].svg);
      })
      .catch(() => {})
      .finally(() => setFetching(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [shapeName]);

  const active = variants[selected];

  return (
    <div style={{
      background: T.card,
      border: `1.5px solid ${T.border}`,
      borderRadius: 16,
      padding: "18px 20px 16px",
      display: "flex", flexDirection: "column", gap: 14,
      height: "100%", boxSizing: "border-box",
      overflow: "hidden",
    }}>

      {/* Header */}
      <div>
        <div style={{ fontSize: 14, fontWeight: 700, color: T.ink, fontFamily: "'Geist', sans-serif" }}>
          Shape Preview
        </div>
        <div style={{ fontSize: 11, color: T.muted, fontFamily: "'Geist', sans-serif", marginTop: 2 }}>
          {displayName} Form{active?.description ? ` · ${active.description}` : ""}
        </div>
        <div style={{ height: 1, background: T.border, marginTop: 10 }} />
      </div>

      {/* Main preview */}
      <div style={{
        flex: 1, minHeight: 160,
        borderRadius: 10,
        background: T.cream,
        display: "flex", alignItems: "center", justifyContent: "center",
        overflow: "hidden", padding: 16, position: "relative",
      }}>
        {fetching && !active?.svg ? (
          <ShimmerBlock width={140} height={140} radius={12} />
        ) : active?.svg ? (
          <div key={`${selected}-${active.svg.length}`} style={{ animation: "fadeIn 0.2s ease" }}>
            <SvgPreview svg={active.svg} size={160} />
          </div>
        ) : (
          <div style={{ textAlign: "center", color: "#BBBBBB" }}>
            <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1">
              <rect x="3" y="3" width="18" height="18" rx="3" />
              <path d="M21 15l-5-5L5 21" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            <div style={{ fontSize: 11, marginTop: 8, fontFamily: "'Geist', sans-serif" }}>No shape</div>
          </div>
        )}
      </div>

      {/* Form gallery */}
      <div style={{ display: "flex", gap: 8 }}>
        {variants.map((v, idx) => {
          const isActive = selected === idx;
          return (
            <button
              key={idx}
              onClick={() => {
                setSelected(idx);
                onSelect?.();
                if (v.svg) onSelectSvg?.(v.svg);
              }}
              style={{
                flex: 1, minWidth: 0,
                display: "flex", flexDirection: "column", alignItems: "center", gap: 6,
                padding: "10px 6px",
                borderRadius: 12,
                border: isActive ? `1.5px solid rgba(21,60,54,0.35)` : `1.5px solid ${T.border}`,
                background: isActive ? "rgba(21,60,54,0.07)" : T.cream,
                cursor: "pointer",
                transition: "border-color 0.15s, background 0.15s",
                outline: "none",
              }}
              onMouseEnter={(e) => {
                if (!isActive) {
                  (e.currentTarget as HTMLElement).style.borderColor = "rgba(21,60,54,0.2)";
                  (e.currentTarget as HTMLElement).style.background = "rgba(21,60,54,0.03)";
                }
              }}
              onMouseLeave={(e) => {
                if (!isActive) {
                  (e.currentTarget as HTMLElement).style.borderColor = T.border;
                  (e.currentTarget as HTMLElement).style.background = T.cream;
                }
              }}
            >
              {/* Thumbnail */}
              <div style={{
                width: 52, height: 52, borderRadius: 8,
                display: "flex", alignItems: "center", justifyContent: "center",
              }}>
                {v.svg ? (
                  <SvgPreview svg={v.svg} size={44} />
                ) : (
                  <ShimmerBlock width={44} height={44} radius={8} />
                )}
              </div>

              {/* Label */}
              <div style={{
                fontSize: 11, fontWeight: isActive ? 700 : 500,
                color: isActive ? T.forest : T.muted,
                fontFamily: "'Geist', sans-serif",
                textAlign: "center",
              }}>
                {v.label}
              </div>
            </button>
          );
        })}
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// Main component
// ─────────────────────────────────────────────────────────────────────────────

type ReviseKind = "recipe" | "shape";

export function Step5ChefV2() {
  const {
    dietitianOutput, chefOutput, prompt, parsedPrompt,
    getSelectedProfile, setParsedPrompt, setChefOutput,
    setEngineerOutput, setStepLoading, setStepError,
    stepLoading, stepError, appendLog, goToStep,
  } = useWizardStore();

  const profile = getSelectedProfile();
  const [showRevise, setShowRevise] = useState<ReviseKind | null>(null);
  const [hasInteracted, setHasInteracted] = useState(false);
  const [selectedSvg, setSelectedSvg] = useState<string | null>(null);

  const isLoading = stepLoading.chef || stepLoading.engineer;
  const error = stepError.engineer;

  async function handleConfirm() {
    if (!chefOutput) return;
    setStepLoading("engineer", true);
    setStepError("engineer", null);
    const t0 = Date.now();
    try {
      // If a specific SVG variant was selected, convert it to b64 PNG for the engineer
      let effectiveChefOutput = chefOutput;
      if (selectedSvg) {
        const b64 = await svgToB64(selectedSvg);
        effectiveChefOutput = { ...chefOutput, silhouette_image_b64: b64 };
      }
      const result = await runEngineer(prompt, effectiveChefOutput, profile?.age ?? 0, parsedPrompt?.meal_type ?? "");
      appendLog({ stage: "engineer",
        request: { prompt, chef_output: effectiveChefOutput },
        response: result as unknown as Record<string, unknown>,
        timestamp: t0, duration_ms: Date.now() - t0 });
      setEngineerOutput(result);
      goToStep(6);
    } catch (err) {
      setStepError("engineer", err instanceof Error ? err.message : "Failed to run engineer.");
    } finally {
      setStepLoading("engineer", false);
    }
  }

  function svgToB64(svg: string): Promise<string> {
    return new Promise((resolve, reject) => {
      const canvas = document.createElement("canvas");
      canvas.width = 512; canvas.height = 512;
      const ctx = canvas.getContext("2d");
      if (!ctx) { reject(new Error("no canvas ctx")); return; }
      const blob = new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const img = new Image();
      img.onload = () => {
        ctx.fillStyle = "white";
        ctx.fillRect(0, 0, 512, 512);
        ctx.drawImage(img, 0, 0, 512, 512);
        URL.revokeObjectURL(url);
        resolve(canvas.toDataURL("image/png").split(",")[1]);
      };
      img.onerror = () => { URL.revokeObjectURL(url); reject(new Error("svg load failed")); };
      img.src = url;
    });
  }

  async function handleRevisePrompt(revision: string) {
    if (!dietitianOutput) return;
    setStepLoading("chef", true);
    setStepError("chef", null);
    const tag = showRevise === "shape" ? "[Shape revision]" : "[Recipe revision]";
    const revisedPrompt = `${prompt}\n\n${tag}: ${revision}`;
    const t0 = Date.now();
    try {
      const parsed = await runParse(revisedPrompt);
      setParsedPrompt(parsed);
      const result = await runChef(
        dietitianOutput.nutrition_targets, dietitianOutput.allergens,
        profile?.age ?? 0, profile?.sex ?? "", profile?.dietaryPreferences ?? [],
        parsed.shape, parsed.meal_type, parsed.ingredients, parsed.menu
      );
      appendLog({ stage: "chef",
        request: { prompt: revisedPrompt, nutrition_targets: dietitianOutput.nutrition_targets },
        response: result as unknown as Record<string, unknown>,
        timestamp: t0, duration_ms: Date.now() - t0 });
      setChefOutput(result);
      setShowRevise(null);
      setHasInteracted(true);
    } catch (err) {
      setStepError("chef", err instanceof Error ? err.message : "Revision failed.");
    } finally {
      setStepLoading("chef", false);
    }
  }

  // Manual slider overrides: build a descriptive prompt and route through AI
  async function handleReviseManual(overrides: Record<string, number>) {
    if (showRevise === "recipe") {
      const parts: string[] = [];
      if (overrides.calories !== undefined) parts.push(`${overrides.calories} kcal`);
      if (overrides.protein !== undefined) parts.push(`${overrides.protein}g protein`);
      if (overrides.sugar !== undefined) parts.push(`max ${overrides.sugar}g sugar`);
      await handleRevisePrompt(`Adjust the recipe to target: ${parts.join(", ")}.`);
    } else if (showRevise === "shape") {
      const scale = overrides.scale ?? 1;
      const desc = scale < 1 ? "smaller" : scale > 1 ? "larger" : "the same size";
      await handleRevisePrompt(`Adjust the printed shape to be ${desc} (scale ${scale}x).`);
    }
  }

  // Derive slider fields from current chef output
  const recipeSliders = chefOutput?.nutrition_facts ? [
    { key: "calories", label: "Calories", min: 50, max: 500, step: 5,
      value: Math.round(chefOutput.nutrition_facts.calories ?? 150), unit: "kcal" },
    { key: "protein", label: "Protein", min: 0, max: 40, step: 0.5,
      value: parseFloat((chefOutput.nutrition_facts.protein_g ?? 5).toFixed(1)), unit: "g" },
    { key: "sugar", label: "Sugar", min: 0, max: 30, step: 0.5,
      value: parseFloat((chefOutput.nutrition_facts.total_sugars_g ?? 3).toFixed(1)), unit: "g" },
  ] : [];

  const shapeSliders = [
    { key: "scale", label: "Scale", min: 0.5, max: 2.0, step: 0.1, value: 1.0, unit: "×" },
  ];

  if (!chefOutput && stepLoading.chef) {
    return (
      <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center" }}>
        <LoadingBlock label="Designing your recipe..." />
      </div>
    );
  }
  if (!chefOutput) return null;

  return (
    <>
      <style>{`@keyframes spin { to { transform: rotate(360deg); } } @keyframes fadeUp { from { opacity:0; transform: translateY(10px); } to { opacity:1; transform: translateY(0); } } @keyframes shimmer { 0% { background-position: -300% 0; } 100% { background-position: 300% 0; } } @keyframes fadeIn { from { opacity:0; } to { opacity:1; } }`}</style>

      <div style={{ flex: 1, display: "flex", flexDirection: "column", minHeight: 0, overflow: "hidden",
        background: "var(--bg)" }}>

        {/* Scrollable content */}
        <div style={{
          flex: 1, overflowY: "auto",
          padding: "32px 28px",
          maxWidth: 1240, margin: "0 auto", width: "100%",
          display: "flex", flexDirection: "column", gap: 24,
          boxSizing: "border-box",
        }}>

          {/* Title */}
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <h2 style={{
              margin: 0, fontSize: 32,
              fontFamily: "'Instrument Serif', serif",
              fontWeight: 400, color: T.ink,
              letterSpacing: "-0.01em",
            }}>
              {chefOutput.menu_name}
            </h2>
            <BookmarkIcon />
          </div>

          {/* 4-column row */}
          <div style={{ display: "flex", gap: 16, alignItems: "stretch" }}>
            {/* Recipe cards */}
            <div style={{
              flex: 1, minWidth: 0, display: "grid",
              gridTemplateColumns: `repeat(${Math.min(chefOutput.syringe_recipes.length, 2)}, minmax(0, 1fr))`,
              gap: 16,
            }}>
              {chefOutput.syringe_recipes.map((r) => (
                <SyringeRecipeCardV2 key={r.syringe_id} recipe={r} />
              ))}
            </div>

            {/* Shape preview */}
            <div style={{ flexShrink: 0, width: 260, display: "flex" }}>
              <ContourPreviewV2
                shapeName={parsedPrompt?.shape ?? ""}
                onSelect={() => setHasInteracted(true)}
                onSelectSvg={(svg) => { setSelectedSvg(svg); setHasInteracted(true); }}
              />
            </div>

            {/* Nutrition facts */}
            {chefOutput.nutrition_facts && (
              <div style={{ flexShrink: 0, display: "flex" }}>
                <NutritionFactsTable facts={chefOutput.nutrition_facts} />
              </div>
            )}
          </div>

          {/* Post-processing */}
          {chefOutput.post_processing?.length > 0 && (
            <div style={{
              padding: "14px 18px", borderRadius: 14,
              background: T.card, border: `1.5px solid ${T.border}`,
            }}>
              <div style={{ fontSize: 10, fontWeight: 600, textTransform: "uppercase",
                letterSpacing: "0.08em", color: T.muted, marginBottom: 6,
                fontFamily: "'Geist Mono', monospace" }}>
                After printing
              </div>
              <div style={{ fontSize: 13, color: T.ink, lineHeight: 1.7,
                fontFamily: "'Geist', sans-serif" }}>
                {chefOutput.post_processing[0]}
              </div>
            </div>
          )}

          {/* KB chunks */}
          {chefOutput.retrieved_chunks && chefOutput.retrieved_chunks.length > 0 && (
            <details>
              <summary style={{
                cursor: "pointer", fontSize: 12, fontWeight: 600, color: T.muted,
                userSelect: "none", marginBottom: 8,
                fontFamily: "'Geist Mono', monospace",
              }}>
                Retrieved KB Chunks ({chefOutput.retrieved_chunks.length})
              </summary>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {chefOutput.retrieved_chunks.map((chunk, i) => (
                  <div key={i} style={{
                    padding: "10px 14px", borderRadius: 10,
                    background: T.card, border: `1.5px solid ${T.border}`,
                    fontSize: 12, color: T.ink, lineHeight: 1.6,
                    fontFamily: "'Geist', sans-serif",
                  }}>
                    <div style={{ fontWeight: 600, color: T.muted, marginBottom: 4, fontSize: 11,
                      fontFamily: "'Geist Mono', monospace" }}>
                      score: {chunk.score.toFixed(4)}
                      {chunk.metadata?.source ? ` · ${chunk.metadata.source}` : ""}
                    </div>
                    <div style={{ whiteSpace: "pre-wrap" }}>{chunk.content}</div>
                  </div>
                ))}
              </div>
            </details>
          )}

          {/* Engineer error */}
          {error && (
            <div style={{
              padding: "12px 16px", borderRadius: 10,
              background: T.dangerBg, border: `1px solid #fcc`,
              color: T.danger, fontSize: 13, fontFamily: "'Geist', sans-serif",
            }}>
              {error}
            </div>
          )}

          {/* ── Always-visible Feedback card ── */}
          <div style={{
            background: T.card, border: `1.5px solid ${T.border}`,
            borderRadius: 16, overflow: "hidden",
          }}>
            {/* Card header + tabs */}
            <div style={{ padding: "18px 20px 14px" }}>
              <div style={{ fontSize: 14, fontWeight: 700, color: T.ink, marginBottom: 12,
                fontFamily: "'Geist', sans-serif" }}>
                Feedback
              </div>
              <div style={{ display: "flex", gap: 8 }}>
                {(["recipe", "shape"] as ReviseKind[]).map((kind) => {
                  const isActive = showRevise === kind;
                  return (
                    <button key={kind}
                      onClick={() => {
                        setShowRevise(isActive ? null : kind);
                        setStepError("chef", null);
                        setHasInteracted(true);
                      }}
                      style={{
                        padding: "7px 18px", borderRadius: 8, fontSize: 13, fontWeight: 600,
                        cursor: "pointer", fontFamily: "'Geist', sans-serif",
                        border: isActive ? `1.5px solid rgba(21,60,54,0.35)` : `1.5px solid ${T.border}`,
                        background: isActive ? "rgba(21,60,54,0.07)" : T.cream,
                        color: isActive ? T.forest : T.muted,
                        transition: "border-color 0.15s, background 0.15s, color 0.15s",
                      }}
                    >
                      {kind.charAt(0).toUpperCase() + kind.slice(1)}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Divider + RevisePanel */}
            {showRevise ? (
              <>
                <div style={{ height: 1, background: T.border }} />
                <div style={{ padding: "16px 20px" }}>
                  <RevisePanel
                    onRevisePrompt={handleRevisePrompt}
                    onReviseManual={handleReviseManual}
                    sliderFields={showRevise === "recipe" ? recipeSliders : shapeSliders}
                    loading={stepLoading.chef}
                    error={stepError.chef}
                    onCancel={() => { setShowRevise(null); setStepError("chef", null); }}
                  />
                </div>
              </>
            ) : (
              <div style={{
                padding: "0 20px 16px",
                fontSize: 12, color: T.muted, fontFamily: "'Geist', sans-serif",
              }}>
                Select a category above to give feedback and regenerate.
              </div>
            )}
          </div>
        </div>

        {/* Bottom bar */}
        <div style={{
          flexShrink: 0,
          background: T.card,
          borderTop: `1.5px solid ${T.border}`,
          padding: "14px 28px",
          display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 12,
        }}>
          {!hasInteracted && (
            <p style={{ margin: 0, fontSize: 12, color: T.muted, fontFamily: "'Geist', sans-serif" }}>
              Select a form or submit feedback to activate
            </p>
          )}
          <Button
            variant="primary"
            size="md"
            loading={stepLoading.engineer}
            disabled={isLoading || (!hasInteracted && !stepLoading.engineer)}
            onClick={handleConfirm}
            style={{
              background: hasInteracted && !isLoading ? T.forest : undefined,
              borderColor: hasInteracted && !isLoading ? T.forest : undefined,
              color: hasInteracted && !isLoading ? T.forestInk : undefined,
              borderRadius: 12,
              fontWeight: 600,
              padding: "11px 24px",
              opacity: hasInteracted || stepLoading.engineer ? 1 : 0.45,
              transition: "opacity 0.2s, background 0.2s",
            }}
          >
            {stepLoading.engineer ? "Generating…" : "Confirm →"}
          </Button>
        </div>
      </div>
    </>
  );
}
