; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Wed Jan 21 2026 13:42:12 GMT-0800 (Pacific Standard Time)

M302 P1 ; Allow cold extrusion
M83 ; Use relative extrusion mode
G92 E0 ; Reset extrusion distance
G1 E1 F20 ; prime extrusion
echo "Prime extrusion. Wait for 5 sec."
G4 S5 ; Wait for 5 seconds