; tpre0.g
; called before tool 0 is selected
;
; generated by RepRapFirmware Configuration Tool v3.6.7 on Wed Jan 21 2026 13:42:12 GMT-0800 (Pacific Standard Time)
; parking coordinates X103 Y374 Z60 U60

var parkX = 103
var parkY = 374
var parkU = 60
var safeY = 250
var safeZ = 80

if move.axes[0].homed && move.axes[1].homed && move.axes[2].homed && move.axes[3].homed
    echo "All axis homed, continuing with tool change"
    if move.axes[2].machinePosition < {var.safeZ}
        echo "Current Z is below safeZ."
        G90 ; absolute positioning
        G53 G1 Z{var.safeZ} F300
    else
        echo "Current Z is at or above safeZ."

    G90 ; absolute positioning
    G53 G1 U0 F300
    G53 G1 Y{var.safeY} F3000
    G53 G1 X{var.parkX} F3000
    G53 G1 Y{var.parkY-20} F3000
    G53 G1 Y{var.parkY} F300
    M400
    G53 G1 U{var.parkU} F300 ; lock
    M400
    G53 G1 Y{var.parkY-20} F300
    G53 G1 Y{var.safeY} F600
else
    echo "Error: Tool change failed, axes are not homed!"